apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  labels:
    app: proxy-client
spec:
  selector:
    app: proxy-client # Debe coincidir con las etiquetas del Pod del Deployment
  ports:
    - protocol: TCP
      port: 8900 # Puerto por el que el Service es accesible DENTRO del cluster
      targetPort: 8900 # Puerto en el que el Pod est√° escuchando (containerPort)
  type: ClusterIP # O LoadBalancer si necesitas acceso externo directo 